sites:
# info about isaacwhite.com & subdomains
  isaacwhite.com:
    git: "git@github.com:isaacwhite/isaacwhite.com.git"
    subdomains:
      mytimes:
        git: "git@github.com:isaacwhite/isaacwhite.com.git"
        files:
          binary:
            source: "mytimes_files.tar.gz"
        database:
          name: "mytimes"
          source: "mytimes.sql.gz"
      scylla:
        git: ""
        database:
          name: "scylla"
          source: "scylla.sql.gz"
# info about solomonhoffman.com & subdomains 
  solomonhoffman.com:
    git: ""
    subdomains:
      dev:
        git: "git@github.com:isaacwhite/solomonhoffman.git"
        files:
          binary:
            source: "hoffman_dev_files.tar.gz"
        database:
          name: "hoffman_dev"
          source: "hoffman_dev.sql.gz"
# info about joshuarobertwhite.com & subdomains
  joshuarobertwhite.com:
    git: ""
    subdomains:
      dev:
        git: ""
        files:
          binary:
            source: "jrw_dev_files.tar.gz"
        database:
          name: "jrw_dev"
          source: "jrw_dev.sql.gz"
# info about karakrakower.com & subdomains
  karakrakower.com:
    git: ""
    subdomains:
      dev:
        git: ""
aws:
  binary:
    remote: "/files"
    local: "/var/www/files"
  databases:
    remote: "/dbs"
    local: "/var/www/dbs"

