sites:
# info about isaacwhite.com & subdomains
  isaacwhite.com:
    git: "git@github.com:isaacwhite/isaacwhite.com.git"
    subdomains:
      mytimes:
        git: "git@github.com:isaacwhite/isaacwhite.com.git"
        files:
          binary:
            source: "mytimes.tar.gz"
            destination: "sites/default/"
            extraction: "tar.gz"
        database:
          source: "mytimes.sql.gz"
          extraction: "gzip"
      scylla:
        git: ""
        database:
          source: "scylla.sql.gz"
          extraction: "gzip"
# info about solomonhoffman.com & subdomains 
  solomonhoffman.com:
    git: ""
    subdomains:
      dev:
        git: "git@github.com:isaacwhite/solomonhoffman.git"
        files:
          binary:
            source: "hoffman_dev.tar.gz"
            destination: "sites/default/"
            extraction: "tar.gz"
        database:
          source: "hoffman_dev.sql.gz"
          extraction: "gzip"
# info about joshuarobertwhite.com & subdomains
  joshuarobertwhite.com:
    git: ""
    subdomains:
      dev:
        git: ""
        files:
          binary:
            source: "jrw_dev.tar.gz"
            destination: "sites/default/"
            extraction: "tar.gz"
        database:
          source: "jrw_dev.sql.gz"
          extraction: "gzip"
# info about karakrakower.com & subdomains
  karakrakower.com:
    git: ""
    subdomains:
      dev:
        git: ""
