sites:
# info about isaacwhite.com & subdomains
  isaacwhite.com:
    git:
      remote: "git@github.com:isaacwhite/isaacwhite.com.git"
    subdomains:
      mytimes:
        git: 
          remote: "git@github.com:isaacwhite/mytimes.git"
        files:
          binary:
            source: "mytimes_files.tar.gz"
        database:
          name: "mytimes"
          source: "mytimes.sql.gz"
        cron:
          minutes: "*"
      scylla:
        git:
          remote: "git@github.com:isaacwhite/scylla.git"
        database:
          name: "scylla"
          source: "scylla.sql.gz"
        cron:
          minutes: "*/5"
# info about solomonhoffman.com & subdomains 
  solomonhoffman.com:
    git:
      remote: "git@github.com:isaacwhite/solomonhoffman.git"
    subdomains:
      dev:
        git:
          remote: "git@github.com:isaacwhite/solomonhoffman.git"
          branch: "develop"
        files:
          binary:
            source: "hoffman_dev_files.tar.gz"
        database:
          name: "hoffman_dev"
          source: "hoffman_dev.sql.gz"
        cron:
          minutes: "*/5"
# info about joshuarobertwhite.com & subdomains
  joshuarobertwhite.com:
    git:
      remote: "git@bitbucket.org:isaacwhite/jrw.git"
    subdomains:
      dev:
        git:
          remote: "git@bitbucket.org:isaacwhite/jrw.git"
          branch: "develop"
        files:
          binary:
            source: "jrw_dev_files.tar.gz"
        database:
          name: "jrw_dev"
          source: "jrw_dev.sql.gz"
        cron:
          minutes: "*/5"
# info about karakrakower.com & subdomains
  karakrakower.com:
    subdomains:
      dev:
aws:
  binary:
    remote: "/files"
    local: "/var/www/files"
  databases:
    remote: "/dbs"
    local: "/var/www/dbs"
backups:
  cron:
    hours: 3

