#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# use dependencies defined in metadata.json
# metadata

# use dependencies defined in Modulefile
# modulefile

# A module from the Puppet Forge
# mod 'puppetlabs-stdlib'
mod 'puppetlabs-stdlib'
mod 'example42-yum'
mod 'puppetlabs-firewall'
mod 'puppetlabs-git'
mod 'puppetlabs-nodejs'
mod 'puppetlabs-mysql'
mod 'petems-swap_file'
mod 'thias-php'
mod 'puppetlabs-ntp'
mod 'puppetlabs-vcsrepo'
mod 'stahnma-epel'

# A module from git
# mod 'puppetlabs-ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# A module from a git branch/tag
# mod 'puppetlabs-apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => '1.4.x'
mod 'jfryman-nginx',
	:git => 'git@github.com:isaacwhite/puppet-nginx.git',
	:ref => '0.2.1a'

# A module from Github pre-packaged tarball
# mod 'puppetlabs-apache', '0.6.0', :github_tarball => 'puppetlabs/puppetlabs-apache'

# more info about this file can be found here: http://librarian-puppet.com/
